[[redirects]]
  from = "/*"
  to = "/"
  status = 200
[build]
  command = "echo '----------- ENVIRONMENT -----------' && env && echo '----------- BUILD -----------' && npm run build"
  # Needed if packages have breaking peer deps that can not be easily fixed in the short term
  # environment = { NPM_FLAGS = "--force" }
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

